CREATE TABLE book
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title            VARCHAR(255)                            NOT NULL,
    author           VARCHAR(255)                            NOT NULL,
    isbn             VARCHAR(255),
    publisher        VARCHAR(255),
    publication_year INTEGER,
    genre            VARCHAR(255),
    CONSTRAINT pk_book PRIMARY KEY (id)
);

CREATE TABLE borrowings
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    book_id     BIGINT                                  NOT NULL,
    borrow_date date                                    NOT NULL,
    due_date    date                                    NOT NULL,
    return_date date,
    CONSTRAINT pk_borrowings PRIMARY KEY (id)
);

CREATE TABLE library_users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    role     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_library_users PRIMARY KEY (id)
);

ALTER TABLE book
    ADD CONSTRAINT uc_book_isbn UNIQUE (isbn);

ALTER TABLE library_users
    ADD CONSTRAINT uc_library_users_username UNIQUE (username);

ALTER TABLE borrowings
    ADD CONSTRAINT FK_BORROWINGS_ON_BOOK FOREIGN KEY (book_id) REFERENCES book (id);

ALTER TABLE borrowings
    ADD CONSTRAINT FK_BORROWINGS_ON_USER FOREIGN KEY (user_id) REFERENCES library_users (id);